{
 "title": "Dashy Dashboard",
 "description": "Dashy collects data from your discord server and exports it to Prometheus to display in a Grafana dashboard",
 "tags": [
  "Dashy",
  "Prometheus",
  "Discord"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "![Dashy](https://cdn.discordapp.com/attachments/748957504666599507/1009744725844164660/Dashy.png)"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "options": {
    "content": "# Dashy\n\nThis is a [Dashy](https://ae.tricked.pro/dashy) dashboard.\nDashy collects data from your discord server and this data can be used to make a dashboard"
   }
  },
  {
   "title": "Numbers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "server_counts{type=~\"channels|emojis|members|bots|roles\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Messages per Minute",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "server_counts{type=\"messages_minute\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active members",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "server_counts{type=\"members_active\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Member Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "server_counts{type=~\"members|members_online\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Suggestion stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "server_suggestions_counts{type=~\"suggestions_active|suggestions_denied|suggestions_accepted\"}",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}