version: "3.6"
volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  monitor-net:
    driver: bridge


services:
  prometheus:
    image: prom/prometheus:latest
    hostname: prometheus
    container_name: prometheus
    networks:
      - monitor-net
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention=200h
    restart: always
    ports:
      - 9090:9090
    expose:
      - 9090
 
  grafana:
    container_name: grafana
    depends_on:
      - prometheus
    networks:
      - monitor-net
    hostname: grafana
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
      - ./provisioning/:/etc/grafana/provisioning/
      - ./dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json
    restart: always
    ports:
      - 3000:3000